### ISSUE TITLE
problem with the added 1536-bit N compatibility in branch rfc5054_compat

### ISSUE THREAD

**Issue by fduncanh** [cocagne/csrp#16]
the entry for 1536 bit N was added in  second place in static struct NGHex global_Ng_constants[]  in srp.c

but was added in last (sixth) place  in enum SRP_NGType in srp.c   

This caused me a lot of grief  in adapting this code (for an Apple Airplay receiver, Apple uses a srp-6a variant) till I located the error...

**Comment by cocagne** [comment]
Fixed the enum in srp.h accordingly. Thanks for the bug report fduncanh. It's been broken for years.
